version: '3'

services:
  api:
    container_name: power-system
    image: power-system-img
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
       - "8080:8080"
    restart: always   

